// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuD6hy2CeUTdsEdlbqkO0ySJv1P-uAGZc',
    appId: '1:637303612231:android:a3f587c40df5cccbd02262',
    messagingSenderId: '637303612231',
    projectId: 'patientconverseai',
    storageBucket: 'patientconverseai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRULrzVwLsh5q4LsZBvmvoxrbcuChasew',
    appId: '1:637303612231:ios:cd11599ce01a864fd02262',
    messagingSenderId: '637303612231',
    projectId: 'patientconverseai',
    storageBucket: 'patientconverseai.appspot.com',
    iosClientId: '637303612231-csfpjjpmrd1c0rjgtup017pku145oktp.apps.googleusercontent.com',
    iosBundleId: 'com.patientConverseAI.app',
  );
}
